# Generated by Django 3.2.6 on 2021-09-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care',
        ),
    ]
